# Generated by Django 4.2.9 on 2026-01-27 05:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(help_text='Twilio Call SID', max_length=100, unique=True)),
                ('from_number', models.CharField(help_text="Caller's phone number", max_length=20)),
                ('to_number', models.CharField(help_text='Called phone number', max_length=20)),
                ('call_status', models.CharField(help_text='Status of the call', max_length=50)),
                ('direction', models.CharField(help_text='Call direction (inbound/outbound)', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Time of call')),
                ('duration', models.IntegerField(blank=True, help_text='Call duration in seconds', null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
