# Generated by Django 4.2.9 on 2026-04-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnedWebAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Original user question when answer was learned')),
                ('normalized_question', models.CharField(db_index=True, max_length=400, unique=True)),
                ('answer_text', models.TextField(help_text='Generated answer text saved for reuse')),
                ('source_url', models.URLField(default='https://www.superior.edu.pk/')),
                ('source_snippets', models.JSONField(blank=True, default=list)),
                ('admin_verified', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
