# Generated by Django 4.2.9 on 2026-05-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_learnedwebanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Enable Twilio incoming call handling')),
                ('account_sid', models.CharField(blank=True, default='', help_text='Twilio Account SID', max_length=128)),
                ('auth_token', models.CharField(blank=True, default='', help_text='Twilio Auth Token', max_length=128)),
                ('phone_number', models.CharField(blank=True, default='', help_text='Twilio phone number (E.164)', max_length=32)),
                ('twiml_app_sid', models.CharField(blank=True, default='', help_text='TwiML App SID for client tokens', max_length=64)),
                ('api_key_sid', models.CharField(blank=True, default='', help_text='Twilio API Key SID (for client tokens)', max_length=128)),
                ('api_key_secret', models.CharField(blank=True, default='', help_text='Twilio API Key Secret (for client tokens)', max_length=256)),
                ('greeting_text', models.TextField(blank=True, default='Hello! This is GenCall AI speaking. Thank you for calling us. We are excited to assist you today.', help_text='Message to speak to inbound callers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
