# Generated by Django 4.2.9 on 2026-06-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_twilioconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='call_source',
            field=models.CharField(choices=[('twilio', 'Twilio'), ('browser', 'Browser')], default='twilio', help_text='Where the call originated from', max_length=20),
        ),
    ]
