/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#340080",
        "inverse-primary": "#6d3bd7",
        "tertiary-container": "#009eb9",
        "secondary-container": "#0566d9",
        "primary": "#d0bcff",
        "error": "#ffb4ab",
        "primary-fixed-dim": "#d0bcff",
        "on-secondary": "#002e6a",
        "on-tertiary": "#003640",
        "on-primary-fixed": "#23005c",
        "outline-variant": "#494454",
        "outline": "#958ea0",
        "on-surface": "#e5e2e1",
        "on-secondary-container": "#e6ecff",
        "inverse-on-surface": "#313030",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "surface-dim": "#131313",
        "secondary-fixed": "#d8e2ff",
        "primary-fixed": "#e9ddff",
        "surface-tint": "#d0bcff",
        "surface-variant": "#353534",
        "surface-container-low": "#1c1b1b",
        "tertiary-fixed-dim": "#4cd7f6",
        "on-secondary-fixed": "#001a42",
        "inverse-surface": "#e5e2e1",
        "tertiary": "#4cd7f6",
        "secondary": "#adc6ff",
        "on-error": "#690005",
        "secondary-fixed-dim": "#adc6ff",
        "surface-bright": "#3a3939",
        "surface-container": "#201f1f",
        "background": "#131313",
        "tertiary-fixed": "#acedff",
        "surface": "#131313",
        "surface-container-lowest": "#0e0e0e",
        "on-background": "#e5e2e1",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "on-tertiary-fixed": "#001f26",
        "on-tertiary-fixed-variant": "#004e5c",
        "on-primary-fixed-variant": "#5516be",
        "on-secondary-fixed-variant": "#004395",
        "primary-container": "#a078ff",
        "on-surface-variant": "#cbc3d7",
        "on-tertiary-container": "#002f38",
        "on-primary": "#3c0091",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "gutter": "24px",
        "stack-xs": "8px",
        "container-max": "1440px",
        "margin-page": "48px",
        "stack-md": "24px",
        "stack-xl": "64px",
        "unit": "4px",
      },
      fontFamily: {
        "body-md": "Inter",
        "h3": "Space Grotesk",
        "label-caps": "Inter",
        "body-lg": "Inter",
        "h1": "Space Grotesk",
        "h2": "Space Grotesk",
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "h3": ["32px", { lineHeight: "1.3", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "h1": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "h2": ["48px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
