create table if not exists public.call_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  duration_seconds integer not null default 0,
  summary text,
  intent text,
  turn_count integer not null default 0,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists idx_call_history_user_created
  on public.call_history (user_id, created_at desc);

alter table public.call_history enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'call_history'
      and policyname = 'Users can read own call history'
  ) then
    create policy "Users can read own call history"
      on public.call_history
      for select
      using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'call_history'
      and policyname = 'Users can insert own call history'
  ) then
    create policy "Users can insert own call history"
      on public.call_history
      for insert
      with check (auth.uid() = user_id);
  end if;
end
$$;
